language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: noticemedan
    token:
      secure: MpAiyVuYC1aJjr4Mfo84m29GdiQSgpZdozuXq+Kej6OL85WwkhrrLd58Ll/SrsxHz9vvwi7q1BmPefYmanaQBc6Q2uibF7FnIA5zuJnkrtAtB5AYx+uHWrBSgB9er+ko2PrKL4AOAlT3lvfWHYlgl3DShoDNKHZFbPHnhzp143OgF+ZX6yUw42a/WQKGBkKXkhP8D9gfXOxm2eob6nuWnxrspZ1LdKK+1A9FXe/GmTen6F0b4LU1vTh180V4F7r6U7rRb0i2HSpa3/Wb8npfEzFsYrDoPXWdN08FVbwnUOtpxjaQXie/cWm7MBssujQbCbZ82XtbvTszF/6vY0Xk4LbdW6LNNScC6Mgbs3BA6GudPmq0kZz+Oj23DzV2B4/a3YIR7yS5DDdYyAPjOsAY2/pue7HAlPfKHMTk1bzlPWQ5Mc/bR3Olno8N50AUQjbCJAAMNWBPnAnx0ay+ZlD64FC9pTPXFHT4uQ3Qp5ykA6jfcATDLznX1rficchrS7KN+mQrrAT77FVG/J5kceEnnVp1QDaRJra+DiuEpNRm1x6Iqr/HoGlpd876ePCHhvUJ3iL8E/eMw+qfJCL8Kxt+v1tIhGMu4R4rInscMxK2rAyR+UHWAQPQKuaz58zIvvaXxlzczoZoKIplGKC0pT+8EcHZ23wyXzvFUt0/ej9+xM0=
#    github_token:
#      secure: C6Sq1UvKjIZSncwQnHfTLJb+/V4xSOFDeIWypeM6qjbVm8X+4O/Y8HdOzR2/TxaBhhxIzsrxglU4u8FSDL/5FXQlIlM41ESWzXeh8FkUvb5mBJW2dWqQwZmS7oVGRRjljim7qHr6t5SZwuV0M4gZRsa6IyFrOa6epj5lEGBg0ToI/5Hwp16PAoemBxy24baYF+hS+SsolIwvK55casw808zdboXVJdKrr9fCtLmo35wtkz1rfSOFfb6C4VZ4k8aOw8kxaAa0Kgxy0KVH2zubGhFk7xXumCp7JCmMorXXrrxMmFFwHcKmPO9HMo/V3qr/mYX6V6kQSwuZ862Dy/CqG+MuBHKjCN+tBiZ3juOdESH+cb4XnDsjCmDOg22ngxbyW1c875POnjT07kVOpkgq3IUWutHD8KMC10UbLAoMtlrbjzyySmqqCMaNaAgkIeJAI041WVp3eEFPYgCOHQNtOSapZr3xiXXgFiZdYAOfpvnW4K9USExmFluEj7YHpimkO2PDbCZ0Z8h40XM4GedSB4MRahzS8KohkDpx9Xu3D3yMmnjOGPaF6njMYQclDZcBJNVFBicucYZcEQeChmknIpIDFMW9TEmnHXMJLDLXmMfz58mw5DLDFwAWf6UKl9ERh49x+uTgMay9elLaD7bGWlhSuwnw0ZmlHC8QhC0B8Ao=

jdk:
- oraclejdk9
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"